name: Update Changelog

on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update CHANGELOG.md
        run: |
          # Create changelog entry
          TAG_NAME=${GITHUB_REF#refs/tags/}
          DATE=$(date +%Y-%m-%d)
          
          # Backup existing changelog
          if [ -f CHANGELOG.md ]; then
            cp CHANGELOG.md CHANGELOG.md.bak
          else
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi
          
          # Add new entry
          {
            echo "# Changelog"
            echo ""
            echo "## [$TAG_NAME] - $DATE"
            echo ""
            echo "${{ github.event.release.body }}"
            echo ""
            if [ -f CHANGELOG.md.bak ]; then
              tail -n +3 CHANGELOG.md.bak
            fi
          } > CHANGELOG.md
          
          rm -f CHANGELOG.md.bak
      
      - name: Commit changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update changelog for ${GITHUB_REF#refs/tags/}" || exit 0
          git push