name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov flake8 bandit pip-audit

      - name: Lint
        run: flake8 src/ --max-line-length=88 --max-complexity=10

      - name: Security scan
        run: |
          bandit -r src/
          pip-audit -r requirements.txt || true

      - name: Run tests
        run: pytest tests/ --cov=src --cov-report=term-missing --cov-fail-under=80
