name: Code Quality

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install black flake8 isort mypy pytest
        pip install -e .

    - name: Format check with Black
      run: black --check --diff src/

    - name: Import sorting check
      run: isort --check-only --diff src/

    - name: Lint with flake8
      run: flake8 src/ --count --statistics

    - name: Type check with mypy
      run: mypy src/ --ignore-missing-imports

    - name: Run tests
      run: pytest tests/ -v

    - name: Security scan
      run: |
        pip install bandit safety
        bandit -r src/ -f json -o bandit-report.json || true
        safety check --json --output safety-report.json || true
