name: Security Monitor

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -e .
        pip install bandit safety
    
    - name: Security scan
      run: |
        bandit -r src/ -f json -o bandit-report.json
        safety check --json --output safety-report.json
    
    - name: Regression test
      run: |
        python -c "from dmps.security import SecurityConfig; assert not SecurityConfig.is_safe_path('../../../etc/passwd')"
        python -c "from dmps.validation import InputValidator; v = InputValidator(); r = v.validate_input('<script>alert(1)</script>'); assert r.warnings"
    
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: '*-report.json'
    
    - name: Notify on failure
      if: failure()
      run: echo "Security regression detected!"